name: sqlfordathirdedition
channels:
  - conda
  - conda-forge
dependencies:
  - python=3.9.5
  - pip
  - python-graphviz
  - pip:
      - pandas==1.2.4
      - psycopg2==2.8.6
      - SQLAlchemy==1.4.18
